project:
  type: website
  output-dir: docs

website:
  title: "Parallel Python"
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: Home
      - href: setup.html
        text: "Setup"
      - text: "Session 1"
        menu:
        - text: "Fundamentals"
          href: notebooks/01a-pandas_fundamentals.html
        - text: "Dask"
          href: notebooks/01b-TransitionToDask.html
        - text: "ScientificComputing"
          href: notebooks/01c-Scientific_Computing.html

  body-footer: "All materials copyright Sydney Informatics Hub, University of Sydney"
          
format:
  html:
    theme: simplex
    css: lesson.css
    toc: true
    code-overflow: wrap
    highlight-style: github




