project:
  type: website
  output-dir: docs

website:
  title: "Parallel Python with Dask"
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: Home
      - href: setup.html
        text: "Setup"
      - text: "Fundamentals"
        href: notebooks/01a-pandas_fundamentals.html
      - text: "Polars Dataframes"
        href: notebooks/polars-intro.html
      - text: "Dask"
        href: notebooks/01b-TransitionToDask.html
      - text: "Scientific Computing"
        href: notebooks/01d-dask_delayed.html

          
format:
  html:
    theme: simplex
    css: lesson.css
    toc: true
    code-overflow: wrap
    highlight-style: github
    
wrap: preserve

execute: 
    output: asis




