project:
  type: website
  output-dir: docs
editor:
  render-on-save: true
execute:
  freeze: auto  # re-render only when source changes  


website:
  title: "Sydney Informatics Hub Course name"
  site-url: https://sydney-informatics-hub.github.io/ParallelPython
  repo-url: https://github.com/Sydney-Informatics-Hub/ParallelPython
  repo-actions: [issue]
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: Home
      - href: setup.html
        text: "Setup"
      - text: "Session 1"
        menu:
        - text: "Fundamentals"
          href: notebooks/01a-pandas_fundamentals.html
        - text: "Dask"
          href: notebooks/01b-dask_demo.html
        - text: "ScientificComputing"
          href: notebooks/01c-Scientific_Computing.html

  body-footer: "All materials copyright Sydney Informatics Hub, University of Sydney"
          
format:
  html:
    theme: simplex
    css: lesson.css
    toc: true
    code-overflow: wrap
    highlight-style: github




