# conda env create -f environment.yml
name: parallel
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - numpy # scientific computing
  - pandas # basic datastructures
  - dask # enables parallel processing via high level pythonic syntax
  - jupyterlab #for interactive visualisation
  - scipy #mathematical algorithms and convenience functions built on the NumPy extension 
  - seaborn # for charts and visuals. provides datsets to learning
  - pip
  - polars #more recent alternative to dask dataframes - 
  - scikit-learn # machine learning possible demo
  - pycaret # maybe use (maybe not)
  - pip:
    - ucimlrepo