---
title: "Parallel Python"
output:
  html_document:
    toc: false
    toc_float: false
---


This course is aimed at researchers, students, and industry professionals who want to learn intermediate python skills applied to scientific computing and data science.


## Trainers
* Kristian Maras (Kris) (MSc Mathematics / Ba Commerce)
* Nathaniel (Nate) Butterworth (PhD Computational Geophysics), nathaniel.butterworth@sydney.edu.au
* Darya Vanichkina (PhD Bioinformatics, SFHEA)
* Tim White (PhD Physics and Astronomy)



## Course pre-requisites and setup requirements

Introductory Python experience recommended. 




## Venue, online via Zoom
Participants will be provided with a Zoom link. Trainers will be broadcasting from Sydney.

#### Zoom etiquette and how we interact

Sessions will be recorded for attendees only, and it is set up to only record the host shared screen and host audio. We will try and get these uploaded to this site as soon as possible. Please interrupt whenever you want! Ideally, have your camera on and interact as much as possible. There will be someone monitoring the chat-window with any questions you would like to post there.  Four hours is a long Zoom session so we have plenty of scheduled breaks combined with a mix of content to be delivered as demos, plus sections as independent exercises, but most of the course will be pretty-hands on with everyone writing their own code. We will use Zoom break-out rooms as needed with the Trainers and participants.


## Code of Conduct
We expect all attendees of our training to follow our code of conduct, including bullying, harassment and discrimination prevention policies.

In order to foster a positive and professional learning environment we encourage the following kinds of behaviours at all our events and on our platforms:

* Use welcoming and inclusive language
* Be respectful of different viewpoints and experiences
* Gracefully accept constructive criticism
* Focus on what is best for the community
* Show courtesy and respect towards other community members

Our full CoC, with incident reporting guidelines, is available [here](https://sydney-informatics-hub.github.io/codeofconduct/).



## General session timings

* A. Intoduction and Revise Python Data Manipulation and Pandas Data Structure
* B. Dask Fundamentals and application to solving data and computationally bounded bottlenecks.
* C. Scientific Computing Demonstration 


## Setup Instructions

All content in this course is designed to run on the existing Dask Binder : 

[Dask Binder](https://examples.dask.org/)

Hence no installation steps are needed prior to the course.

